config/routes.rb
App::Application.routes.draw do

  match '/impressum' => "home#imprint"
  match '/sitemap' => "home#sitemap"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match '/admin/helden' => 'admin/helden#update', via: :post

  match '/neue-geschenkidee' => 'products#new', :as => :new_product
  match '/geschenk/suche' => 'products#search', :as => :product_search
  match '/geschenk/:slug' => 'products#show', :as => :product, :via => :get
  match '/geschenk/:slug/bearbeiten' => 'products#edit', :as => :edit_product
  match '/geschenk/:slug/neuer-kommentar' => 'products#add_comment', :as => :add_comment_product
  match '/geschenk/:slug/loeschen' => 'products#delete', :as => :delete_product
  resources :products, :path => "geschenk" do   
    collection do
      post 'find_images', :as => :find_images
    end
    get '/count_likes' => 'products#count_likes'
  end

  get '/show_modal' => 'application#show_modal'

  match '/angemeldet' => 'users#signed_up'
  match '/helden' => 'users#index', :as => :users
  match '/helden/:id' => 'users#show', :as => :user
  match '/profil' => 'users#edit', :as => :profile
  match "/users/sign_up" => "home#index"
  match "/users/sign_in" => "home#index"
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "users/registrations",
  }

  devise_scope :user do
    match 'abmelden', :to => 'devise/sessions#destroy', :as => 'signout'    
  end
  
  match '/wunschzettel/erstellen' => 'lists#create', :as => :create_list
  match '/wunschzettel/hinzufuegen' => 'lists#add_product_to_list', :as => :add_product_to_list
  match '/wunschzettel/:permalink' => 'lists#show', :as => :list
  match '/wunschzettel' => 'lists#index', :as => :lists

   # TRACKING
  post '/track/click' => 'products#track_click'

  match "/eigene-geschenkideen" => 'products#own', :as => :own_products
  match "/:slug(/seite-:page)(/:sort)(/preis-:price)" => 'products#index', :as => :product_category

  root :to => "home#index"
end

app/models/product.rb
# encoding: utf-8

class Product < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  attr_accessible :clicks, :description, :name, :price, :slug, :url, :user_id, :fb_likes
  attr_accessible :image, :remote_image_url, :root_url
  attr_accessible :criteria

  before_create :setup_slug

  validates_uniqueness_of :url, :name, :slug
  validates_presence_of :name, :description, :url, :image, :price, :root_url
  validates_length_of :name, :minimum => 3, :maximum => 60
  validates_length_of :description, :minimum => 3, :maximum => 180

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :lists

  mount_uploader :image, ImageUploader
  process_in_background :image

  serialize :criteria#, Hash

  # tire.mapping do
  #   indexes :id,          :type => 'integer'
  #   indexes :user_id,     :type => 'integer', :index => 'not_analyzed'
  #   indexes :user_image,  :index => 'not_analyzed'
  #   indexes :user_name,   :index => 'not_analyzed'
  #   indexes :name
  #   indexes :image
  #   indexes :slug
  #   indexes :description
  #   indexes :clicks,      :type => 'integer'
  #   indexes :price,       :type => 'float'
  #   indexes :created_at,  :type => 'date'
  #   indexes :updated_at,  :type => 'date'
  # end

  def to_indexed_json

     string_criteria = criteria.to_s
     criteria = eval(string_criteria)
    criteria ||= {}
    maps = {
      :name   => name,
      :slug => slug,
      :description => description,
      :user_id => user_id,
      :user_name => user.name,
      :user_image => user.image,
      :price => price.to_f,
      :url => url,
      :clicks => 0,
      :image => {
        :url => image.url(:thumb)
      },
      :created_at => created_at,
      :updated_at => updated_at,
      :fb_likes => fb_likes
    }.merge(criteria)

    return maps.to_json
  end

  def self.search(params, criteria=nil)
    case params[:sort]
    when "preis-aufsteigend"
      sortfield = "price"
      sortorder = "asc"
    when "preis-absteigend"
      sortfield = "price"
      sortorder = "desc"
    when "neuste-zuerst"
      sortfield = "created_at"
      sortorder = "desc"
    else
      sortfield = "fb_likes"
      sortorder = "desc"
    end

    if params[:price] && params[:price] != ""
      if params[:price].include? "bis"
        operator = "lt"
      else
        operator = "gte"
      end
      price = params[:price].split("-")[1].to_f + 0.01
    end

    tire.search(page: params[:seite], per_page: params[:per_page] ||= 12) do
      query { string params[:query], default_operator: "AND" } if params[:query].present?
      unless criteria.nil?
        criteria.each do |name, value|
          filter :term, name.to_sym => "1" unless value == "0"
        end
      end
      unless params[:ids].nil?
        filter :ids, :values => params[:ids] unless params[:ids].length < 1
      end
      filter :term, :user_id => params[:user_id] unless params[:user_id].nil?
      filter :range, :price => {operator.to_sym => price.to_f} unless price.nil?
      sort { by sortfield.to_sym, sortorder }

      # raise to_json
      # raise to_curl
    end

  end

  def price=(price)
    write_attribute(:price, price.gsub(',', '.'))
  end

  private

  def setup_slug
    if self.slug.nil?
      self.slug = self.name.gsub("ä", "ae").gsub("ö", "oe").gsub("ü", "ue").parameterize
    end
  end

end

app/controllers/products_controller.rb
# encoding: utf-8
require 'koala'
require 'nokogiri'
require 'open-uri'
require 'uri'

class ProductsController < ApplicationController

  before_filter :authenticate_user!, :only => [:own, :new, :edit, :update, :create, :delete, :add_comment]

  def index
    @coocie_module = CoocieModule.first
    @coocie = @coocie_module.body
    if params["utf8"] && params[:query] == nil
      vars = {}
      vars[:slug] = params[:slug]
      if params[:sort] && params[:sort] != ""
        vars[:sort] = params[:sort]
      end
      if params[:price] && params[:price] != ""
        vars[:price] = params[:price]
      end
      redirect_to product_category_path(vars)
    end

    if params[:slug] == "neue-geschenkideen"
      @category = "1"
      @title = "Neue Geschenkideen auf GeschenkeHeld.de | Die Geschenke-Community"
      @h2 = "Die neusten Geschenkideen"
      if params[:sort] == nil
        params[:sort] = "neuste-zuerst"
      end
      @products = Product.search(params)
    else
      @category = Category.find_by_slug(params[:slug])
      if @category
        @products = Product.search(params, @category.criteria)
        @title = @category.name
        @description = @category.description
      else
        @products = Product.search(params)
        if params[:query]
          @title = "Suche nach #{params[:query]}"
        else
          @title = "Geschenkideen"
        end
      end
    end

    # legacy check
    if @category.nil?
      @legacy = LegacyLink.find_by_slug(params[:slug])
      if @legacy
        redirect_to @legacy.new_url, :status => 301
      else
        render :file => "#{Rails.root}/public/404.html", :layout => false, :status => 404
      end
    end
  end

  def search
    @products = Product.search(params)
    @title = "Suche nach #{params[:query]}"
    render "products/index"
  end

  def new
    @product = Product.new
    @title = "Neue Geschenkidee"
  end

  def edit
    @product = current_user.products.find_by_slug(params[:slug])
    @title = "#{@product.name} bearbeiten"
  end

  def show
    @product = Product.find_by_slug(params[:slug])
    if @product
      @title = "#{@product.name} auf GeschenkeHeld.de | Die Geschenke-Community"
    else
      redirect_to '/neue-geschenkideen'
    end
  end

  def own
    @user = current_user
    params[:ids] = @user.products.map(&:id) # TO-DO: Let ES look for user_id
    params[:sort] = "neuste-zuerst" if params[:sort].nil?
    @products = Product.search(params)
    @title = "#{@products.total} eigene Geschenkideen auf GeschenkeHeld.de"
    render 'byuser'
  end

  def update
    @product = current_user.products.find(params[:id])
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price = params[:product][:price]
    @product.criteria = params[:product][:criteria]
    @product.root_url = URI.parse(URI.encode(@product.url)).host
    if @product.save
      flash[:notice] = 'Geschenkidee wurde aktualisiert!'
      redirect_to :action => 'show', :slug => @product.slug
    else
      render :action => 'edit'
    end
  end

  def create
    @product = current_user.products.new(params[:product])
    @product.price = params[:product][:price].gsub(",", ".")
    @product.root_url = URI.parse(URI.encode(@product.url)).host
    if @product.save
      current_user.points += 5
      current_user.save
      redirect_to product_path(@product.slug)
    else
      render :new
    end
  end

  def delete
    @product = current_user.products.find_by_slug(params[:slug])
    if @product
      @product.destroy
    end
    redirect_to own_products_path
  end

  def find_images
    url = params[:url]
    if params[:url]
      doc = Nokogiri::HTML(open(url).read)
      @results = []
      doc.xpath("//img/@src").each do |src|
        @results.push(make_absolute(src, url))
      end
    end
  end

  def add_comment
    @product = Product.find_by_slug(params[:slug])
    if @product
      @comment = @product.comments.new
      @comment.user = current_user
      @comment.content = params[:content]
      if @comment.save
        current_user.points += 5
        current_user.save
        flash[:notice] = "Kommentar erfolgreich hinzugefügt!"
      end
    end
    redirect_to :back
  end

  def track_click
    @product = Product.find_by_slug(params[:slug])
    if @product
      if session["product-#{@product.id}"].nil?
        @product.user.update_attribute(:points, @product.user.points + 1)
        session["product-#{@product.id}"] = true
      end
    end
    render :json => "OK"
  end

  # def likes_count
  #   product = Product.find(params[:product_id])
  #   if !current_user.nil?
  #     @facebook ||= Koala::Facebook::API.new(session["devise.facebook_data"].credentials.token)
  #     block_given? ? yield(@facebook) : @facebook
  #     shares = @facebook.get_object('', id: 'http://www.geschenkeheld.de' + "#{product_path(product.slug)}")["shares"]
  #     puts shares
  #     if product.fb_likes != shares
  #       product.fb_likes = shares
  #       product.save
  #     end
  #     redirect_to :back
  #   else
  #     redirect_to :back
  #   end
  # rescue Koala::Facebook::APIError
  #   logger.info
  #   nil
  # end

  def count_likes
    product = Product.find(params[:product_id])
    ip_address = IpAddress.find_by_ip(request.remote_ip)
    @rating_product = RatingProduct.where(product_id: params[:product_id], ip_address_id: ip_address.id, liked: true)
    if @rating_product === []
      @rating_product = RatingProduct.new(product_id: params[:product_id], evaluation: params[:evaluation], ip_address_id: ip_address.id, liked: true)
      if @rating_product.save
        save_product_likes(params[:product_id])
        product = Product.find(params[:product_id])
        render json: {likes: product.fb_likes}
      end
    else
      # id_rating_product = @rating_product[0].id
      # @rating_product = RatingProduct.find(id_rating_product)
      # @rating = @rating_product.update_attributes(evaluation: params[:evaluation])
      # save_product_likes(params[:product_id])
      # product = Product.find(params[:product_id])

      render json: {flag: false}
    end
  end

  private

  def save_product_likes(product_id)
    @count_evaluation = 0.0
    product = Product.find(product_id)
    @rating_product = RatingProduct.where(product_id: product_id)
    @count_rating_product = @rating_product.count
    @rating_product.each do |i|
      @count_evaluation = @count_evaluation + i.evaluation
    end
    like = @count_evaluation/@count_rating_product
    product.fb_likes = like
    product.save
  end

  def make_absolute(href, root)
    begin
      return URI.parse(URI.encode(root)).merge(URI.parse(href)).to_s
    rescue
      return nil
    end
  end

end

app/views/products/_form.html.erb
<% if @product.errors.full_messages.any? %>
  <div id="errors">
    <h3>Oops, ein paar Probleme, aber nichts schlimmes...</h3>
    <% @product.errors.full_messages.each do |error| %>
    <div class="error">
      <%= error %>
    </div>
    <% end %>
  </div>
  <% end %>

  <% if @product.new_record? %>
  <div class="step">
    <h3>Internet-Adresse eingeben</h3>
    <div class="content" id="url">
      <%= form_tag find_images_products_path, :remote => true do %>
        <input type="text" name="url" id="url-value" placeholder="http://..." value="<%= @product.url %>" />
        <%= button_tag(:type => 'submit', :class => "btn btn-red") do %>
          <i class="icon icon-search"></i> Bilder suchen
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="step <%= 'disabled' if @product.new_record? && @product.errors.full_messages.any? == false %>">
    <h3>Bild auswählen</h3>
    <div class="loading">
      Noch keine Adresse eingegeben
    </div>
    <div class="content" id="images">
      <% unless @product.url == "" || @product.url.nil? %>
        <img src='/assets/loading.gif' alt='Loading' />
      <% end %>
    </div>
  </div>
  <% end %>

  <%= form_for @product do |f| %>
    <%= f.hidden_field :url %>
    <%= f.hidden_field :remote_image_url %>
    <div class="step <%= 'disabled' if @product.new_record? && @product.errors.full_messages.any? == false %>">
      <h3>Geschenk beschreiben</h3>
      <div class="loading">
        Noch kein Bild ausgewählt
      </div>
      <div class="content" id="info">
        <div class="field wide">
          <%= f.label :name, "Titel der Geschenkidee" %>
          <%= f.text_area :name, :rows => 3, :data => {:target => "preview-name"}%>
        </div>

        <div class="field wide">
          <%= f.label :description, "Beschreibung in 1-2 Sätzen" %>
          <%= f.text_area :description, :rows => 3, :data => {:target => "preview-description"} %>
        </div>

        <div class="field">
          <%= f.label :price, "Preis in Euro" %>
          <%= f.text_field :price, :placeholder => "Zum Beispiel: 10,40", :data => {:target => "preview-price"} %>
        </div>

        <div id="categories">
          <%= render :partial => "shared/criteria", :locals => {:model_name => "product", :object => @product} %>
        </div>
      </div>  
    </div>

    <% unless @product.new_record? %>
    <div id="product-delete">
      Oder möchtest Du diese Geschenkidee
      <%= link_to "löschen?", delete_product_path(@product.slug), :confirm => "Bist Du sicher?" %>
    </div>
    <% end %>

    <div id="finish">
      <div class="product">
        <div class="product-image">
          <% if @product.new_record? %>
            <img id="preview-image" src="http://www.placehold.it/300x100&amp;text=Platzhalter" %>
          <% else %>
            <%= image_tag @product.image.url(:thumb) %>
          <% end %>
        </div>
        <div class="product-description">
          <a href="#" id="preview-name"><%= @product.name || "Noch kein Name" %></a>
          <p id="preview-description">
            <%= @product.description || "Noch keine Beschreibung" %>
          </p>
        </div>
        <div class="product-actions">
          <a href="#">Für <span id="preview-price"><%= number_with_precision(@product.price, :precision => 2) || "0.00" %></span>&euro; gefunden</a>
        </div>
        <div class="product-user-list">
          <img src="<%= current_user.image %>" />
          <a href="#" class="product-user-name"><%= current_user.name %></a>
          <div class="product-user-rank"><i class="icon icon-star"></i> <%= current_user.points %></div>
        </div>
      </div>

      <div id="send" class="arrow_box">
        <%= f.submit "Okay, jetzt absenden!", :onClick => "mixpanel.track('Neues Geschenk');" %>
      </div>
    </div>
  <% end %>


<% content_for :javascript do %>  
  <script type="text/javascript">
    $(document).ready(function() {

      $("#url form").on('submit', function(event) {
        $("#images").siblings(".loading").html("<img src='/assets/loading.gif' alt='Loading' />");
      });

      console.log($("#url-value").val());

      if($("#url-value").val() != "") {
        $("#url form").submit();
      }

      $("#new_product textarea, #new_product input").on("keyup", function(event) {
        $("#" + $(this).data('target')).html($(this).val());
      });

      $("#images").on('click',".image", function() {
        $("#images .image.active").removeClass("active");
        $(this).addClass("active");
        $("#product_remote_image_url").val($(this).find("img").first().attr("src"));
        $("#preview-image").attr("src", $(this).find("img").first().attr("src"));
        $("#info").parent(".step").removeClass("disabled");
      });

      var bt = $('#finish').position().top;
      var threshold = $("#finish").offset().top;

      $(window).scroll(function() {
        var wst = $(window).scrollTop();

        if(wst <= threshold) {
          $('#finish').css({position: 'absolute', top: bt +'px', bottom: 'auto' });
        }
        if(wst >= threshold) {
          $('#finish').css({position: 'absolute', top: (wst - threshold + bt + 10) +'px', bottom: 'auto' });
        }
        if(Math.abs(wst - $("#products").height() - $("#products").offset().top) < $("#finish").height()) {
          $('#finish').css({position: 'absolute', top: 'auto', bottom: '55px' });
        }        
      });
    });
  </script>
<% end %>

app/views/products/show.html.erb
<script type="text/javascript">

    $(document).ready(function(){

        $('#evaluation').raty({
            click: function(score, evt) {
                $.ajax({
                    type: 'GET',
                    dataType: 'JSON',
                    url: '<%= product_count_likes_path(@product.id) %>',
                    data: { evaluation: score },
                    success: function (data) {
                        if (data.flag === false)
                        {
                            alert(" Sie haben Ihre Bewertung bereits hinterlassen.")
                        }else
                        {
                            $("#evaluation .show_evaluation span").text(data.likes);
                        }
                    }
                });
            }
        });
    });


</script>
<div id="products">

  <% if @product.user == current_user %>
      <div id="product-edit">
        <i class="icon icon-info-sign"></i> Dies ist Deine Geschenkidee. Möchtest Du sie
        <a href="<%= edit_product_path(@product.slug) %>">bearbeiten oder löschen?</a>
      </div>
  <% end %>

  <h2><%= @product.name %></h2>

  <div id="product-info">
    <a href="<%= @product.url %>" class="go" rel="nofollow" target="_blank" onClick="mixpanel.track('Zum Anbieter',{'slug':'<%= @product.slug %>'});_gaq.push(['_trackPageview', '/zum-anbieter/#{product.slug}']);" data-slug="<%= @product.slug %>"><i class="icon icon-shopping-cart"></i>
      Für <%= price(@product.price) %> auf <%= @product.root_url %> gefunden</a>
  </div>

  <div id="product-sidebar">
    <div id="product-image">
      <%= image_tag @product.image, :alt => @product.name %>
    </div>
    <!--<div id="product-socials">-->


      <!--<div class="fb-like"-->
           <!--data-href="<%#= "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>"-->
           <!--data-layout="button_count"-->
           <!--data-action="like"-->
           <!--data-show-faces="true"-->
           <!--data-share="false">-->

      <!--</div>-->

    <!--</div>-->
    <div id="social_services">

      <div id="evaluation">
        <p class="show_evaluation">
          <span><%= @product.fb_likes.round(1) %></span>
        </p>
      </div>
      <div class="shariff"
           data-url= <%= "#{product_url}" %>
                   data-title= <%= "#{@product.name}" %>
           data-theme="standard"
           data-services="[&quot;facebook&quot;,&quot;whatsapp&quot;,&quot;googleplus&quot;,&quot;twitter&quot;,&quot;pinterest&quot;,&quot;tumblr&quot;]" >
      </div>
    </div>
    <h3>Zeige dieses Geschenk Deinen Freunden!</h3>
  </div>

  <div id="product-comments">
    <div class="comment">
      <div class="comment-user">
        <%= image_tag @product.user.image, :alt => @product.user.name %>
        <a href="" class="comment-user-name"><%= @product.user.name %></a>

        <div class="product-user-rank"><i class="icon icon-star"></i> <%= @product.user.points %></div>
      </div>
      <div class="comment-content">
        <%= @product.description %>
      </div>
    </div>

    <% @product.comments.each do |comment| %>
        <div class="comment">
          <div class="comment-user">
            <%= image_tag comment.user.image, :alt => comment.user.name %>
            <a href="" class="comment-user-name"><%= comment.user.name %></a>

            <div class="product-user-rank"><i class="icon icon-star"></i> <%= comment.user.points %></div>
          </div>
          <div class="comment-content">
            <%= comment.content %>
          </div>
        </div>
    <% end %>

    <% if user_signed_in? %>
        <div id="new-product-comment">
          <%= form_tag add_comment_product_path(@product.slug) do %>
              <div class="comment">
                <div class="comment-user">
                  <%= image_tag current_user.image, :alt => current_user.name %>
                  <a href="" class="comment-user-name"><%= current_user.name %></a>

                  <div class="product-user-rank"><i class="icon icon-star"></i> <%= current_user.points %></div>
                </div>
                <div class="comment-content">
                  <textarea name="content" rows="1" placeholder="Neuen Kommentar verfassen..."></textarea>
                </div>
                <div class="comment-actions">
                  <%= submit_tag "Kommentar hinzufügen", :class => "btn btn-success" %>
                </div>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.6";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!--<div id="fb-root"></div>-->
<!--<script>-->
<!--//    (function (d, s, id) {-->
<!--//        var js, fjs = d.getElementsByTagName(s)[0];-->
<!--//        if (d.getElementById(id)) return;-->
<!--//        js = d.createElement(s);-->
<!--//        js.id = id;-->
<!--//        js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1&appId=102969429752310";-->
<!--//        fjs.parentNode.insertBefore(js, fjs);-->
<!--//    }(document, 'script', 'facebook-jssdk'));-->
<!--</script>-->


<!--<%# content_for :javascript do %>-->
<!--<script type="text/javascript">-->
<!--//        $(document).ready(function () {-->
<!--//            $('textarea').autosize();-->
<!--//        });-->
<!--&lt;!&ndash;</script>&ndash;&gt;-->

app/views/products/show.mobile.erb
<script type="text/javascript">

    $(document).ready(function(){

        $('#evaluation').raty({
            click: function(score, evt) {
                $.ajax({
                    type: 'GET',
                    dataType: 'JSON',
                    url: '<%= product_count_likes_path(@product.id) %>',
                    data: { evaluation: score },
                    success: function (data) {
                        if (data.flag === false)
                        {
                            alert(" Sie haben Ihre Bewertung bereits hinterlassen.")
                        }else
                        {
                            $("#evaluation .show_evaluation span").text(data.likes);
                        }
                    }
                });
            }
        });
    });

</script>

<div id="products">

  <% if @product.user == current_user %>
      <div id="product-edit">
        <i class="icon icon-info-sign"></i> Dies ist Deine Geschenkidee. Möchtest Du sie
        <a href="<%= edit_product_path(@product.slug) %>">bearbeiten oder löschen?</a>
      </div>
  <% end %>

  <h2><%= @product.name %></h2>

  <div id="product-info">
    <a href="<%= @product.url %>" class="go" rel="nofollow" target="_blank" onClick="mixpanel.track('Zum Anbieter',{'slug':'<%= @product.slug %>'});_gaq.push(['_trackPageview', '/zum-anbieter/#{product.slug}']);" data-slug="<%= @product.slug %>"><i class="icon icon-shopping-cart"></i>
      Für <%= price(@product.price) %> auf <%= @product.root_url %> gefunden</a>
  </div>

  <div id="product-sidebar">
    <div id="product-image">
      <%= image_tag @product.image, :alt => @product.name %>
    </div>
    <!--<div id="product-socials">-->

      <!--<div class="fb-like"-->
           <!--data-href="<%#= "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>"-->
           <!--data-layout="button_count"-->
           <!--data-action="like"-->
           <!--data-show-faces="true"-->
           <!--data-share="false">-->

      <!--</div>-->

    <!--</div>-->
    <div id="social_services">

      <div id="evaluation">
        <p class="show_evaluation">
          <span><%= @product.fb_likes.round(1) %></span>
        </p>
      </div>
      <div class="shariff"
           data-url= <%= "#{product_url}" %>
                   data-title= <%= "#{@product.name}" %>
           data-theme="standard"
           data-services="[&quot;facebook&quot;,&quot;whatsapp&quot;,&quot;googleplus&quot;,&quot;twitter&quot;,&quot;pinterest&quot;,&quot;tumblr&quot;]" >
      </div>
    </div>
    <h3>Zeige dieses Geschenk Deinen Freunden!</h3>
  </div>

  <div id="product-comments">
    <div class="comment">
      <div class="comment-user">
        <%= image_tag @product.user.image, :alt => @product.user.name %>
        <a href="" class="comment-user-name"><%= @product.user.name %></a>

        <div class="product-user-rank"><i class="icon icon-star"></i> <%= @product.user.points %></div>
      </div>
      <div class="comment-content">
        <%= @product.description %>
      </div>
    </div>

    <% @product.comments.each do |comment| %>
        <div class="comment">
          <div class="comment-user">
            <%= image_tag comment.user.image, :alt => comment.user.name %>
            <a href="" class="comment-user-name"><%= comment.user.name %></a>

            <div class="product-user-rank"><i class="icon icon-star"></i> <%= comment.user.points %></div>
          </div>
          <div class="comment-content">
            <%= comment.content %>
          </div>
        </div>
    <% end %>

    <% if user_signed_in? %>
        <div id="new-product-comment">
          <%= form_tag add_comment_product_path(@product.slug) do %>
              <div class="comment">
                <div class="comment-user">
                  <%= image_tag current_user.image, :alt => current_user.name %>
                  <a href="" class="comment-user-name"><%= current_user.name %></a>

                  <div class="product-user-rank"><i class="icon icon-star"></i> <%= current_user.points %></div>
                </div>
                <div class="comment-content">
                  <textarea name="content" rows="1" placeholder="Neuen Kommentar verfassen..."></textarea>
                </div>
                <div class="comment-actions">
                  <%= submit_tag "Kommentar hinzufügen", :class => "btn btn-success" %>
                </div>
              </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.6";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!--<div id="fb-root"></div>-->
<!--<script>-->
<!--//    (function (d, s, id) {-->
<!--//        var js, fjs = d.getElementsByTagName(s)[0];-->
<!--//        if (d.getElementById(id)) return;-->
<!--//        js = d.createElement(s);-->
<!--//        js.id = id;-->
<!--//        js.src = "//connect.facebook.net/de_DE/all.js#xfbml=1&appId=102969429752310";-->
<!--//        fjs.parentNode.insertBefore(js, fjs);-->
<!--//    }(document, 'script', 'facebook-jssdk'));-->
<!--</script>-->


<!--<%# content_for :javascript do %>-->
    <!--<script type="text/javascript">-->
<!--//        $(document).ready(function () {-->
<!--//            $('textarea').autosize();-->
<!--//        });-->
    <!--&lt;!&ndash;</script>&ndash;&gt;-->